# Dependencies
markdown: kramdown
kramdown:
   math_engine: mathjax

highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Roshan's Blog
description:      'Giving my perspective on the world and things around through my experience, interaction and my camera lens'
url:              http://roshrestha.github.io
baseurl:          /

author:
  name:           'Roshan Shrestha'
  url:            https://twitter.com/roshan_shrestha

paginate:         5
plugins:
  - jemoji

# Custom vars
# math_engine: jekyll-katex

